export const testimonials = [
  {
    id: 1,
    name: "Mohammed Hassan",
    location: "London, UK",
    text: "I've tried many online platforms, but the Tajweed lessons here are exceptional. The teachers ensure perfect pronunciation.",
    rating: 5,
    course: "Nazeera",
    avatar: "M",
  },
  {
    id: 2,
    name: "Sarah Ahmed",
    location: "Dubai, UAE",
    text: "The Noorani Qaida course helped me start my Quran learning journey. The teachers are patient and the lessons are well-structured.",
    rating: 5,
    course: "Noorani Qaida",
    avatar: "S",
  },
  {
    id: 3,
    name: "Aisha Patel",
    location: "Toronto, Canada",
    text: "The Hifz program is comprehensive and the mentors are very supportive. I've memorized 5 Juz in just 6 months!",
    rating: 5,
    course: "Hifz",
    avatar: "A",
  },
  {
    id: 4,
    name: "Omar Khan",
    location: "New York, USA",
    text: "I struggled with Tajweed before, but the structured lessons here made it so easy to learn. Highly recommended!",
    rating: 5,
    course: "Tajweed",
    avatar: "O",
  },
  {
    id: 5,
    name: "Fatima Siddiqui",
    location: "Sydney, Australia",
    text: "Alhamdulillah! The Quran recitation classes have improved my fluency and confidence. The teachers are amazing.",
    rating: 5,
    course: "Quran Recitation",
    avatar: "F",
  },
  {
    id: 6,
    name: "Yusuf Ali",
    location: "Doha, Qatar",
    text: "The one-on-one learning sessions are perfect for personalized guidance. The tutors are very knowledgeable and kind.",
    rating: 5,
    course: "One-on-One Quran Classes",
    avatar: "Y",
  },
  {
    id: 7,
    name: "Zainab Bukhari",
    location: "Karachi, Pakistan",
    text: "The Islamic studies course helped me deepen my understanding of my faith. The interactive approach makes learning engaging!",
    rating: 5,
    course: "Islamic Studies",
    avatar: "Z",
  },
];
